name: 'dbt_analytics'
version: '1.0.0'
config-version: 2

# Perfil de conexión
profile: 'default'

# Rutas del proyecto
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Directorios de salida
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuración de modelos
models:
  dbt_analytics:
    staging:
      +materialized: table
      +tags: ["Staging"]
    processing:
      +materialized: view
      +tags: ["processing"] 
    mart:
      +materialized: view
      +tags: ["mart"]   
