SELECT
    TRY_CAST(SALESDATE AS DATE) AS DDATE,
    SALESPERSON,
    CUSTOMERNAME,
    CARMAKE,
    CARMODEL,
    TRY_CAST(CARYEAR AS NUMBER) AS CARYEAR,
    SALEPRICE,
    COMMISSIONRATE AS COMRATE,
    COMMISSIONEARNED AS COMNEA
FROM {{ source("raw_bi_car","CAR_SALES")}}
WHERE TRY_CAST(SALESDATE AS DATE) > '2020-01-01' 