-- ESTE TEST PASA SI LA CONSULTA DEVUELVE 0 FILAS
-- SELECCIONA CUALQUIER REGISTRO DE LA TABLA DE HECHOS DONDE LAS METRICAS SEAN NEGATIVAS

SELECT
    DDATE,
    ID_SALESPERSON,
    ID_CARMAKE,
    TOTAL_SALE,
    TOTAL_COM
FROM {{ ref("fct_montly_sales") }}
WHERE 
    TOTAL_SALE < 0 OR TOTAL_COM < 0  